# Manhattan and heatmap eDNA---------------------------------------------------
#' @title qpcr_fig
#' @description The function generates a Manhattan and/or Heatmap figure
#' for frequency eDNA data
#' @param data (object). Data generated by \code{\link{read_edna}}.
#' @param manhattan (optional, logical). Generate the manhattan plot.
#' Default: \code{manhattan = TRUE}.
#' @param heatmap (optional, logical). Generate the heatmap plot.
#' Default: \code{heatmap = TRUE}.
#' @param ecoregion.select (optional, character, string) If not supplied,
#' all the ecoregions in the data are used. To focus on fewer ecoregions,
#' list with this argument.
#' Default: \code{ecoregion.select = NULL}.
#' @param taxon.select (optional, character) Select one of the taxon.
#' Available values: \code{taxon.select = c("KINGDOM", "PHYLUM", "CLASS", "ORDER",
#' "FAMILY", "GENUS", "SCIENTIFIC_NAME", "SPP")}. With default the visualization
#' is generated for all taxon combined.
#' Default: \code{taxon.select = NULL}.
#' @param species.select (optional, character, string) If not supplied,
#' all the species available in the data are used. To focus on fewer species,
#' select and list the species with this argument. The name must be taken from
#' the column \code{SPP}, e.g. H. americanus.
#' Default: \code{species.select = NULL}.

#' @param year (optional, logical) To display the variable year in the figure.
#' Default: \code{year = FALSE}.
#' @param year.select (optional, integer, string) Select specific years to
#' display in the figure. By Default, all years available will be used, conditional
#' to \code{year = TRUE} is enabled.
#' Default: \code{year.select = NULL}.
#' @param x.axis (optional, character) By default the x axis display the variable month.
#' Using \code{x.axis = "SPP"}, will trigger the function to display the facet grid
#' by species on the x-axis and ecoregions using all months combined.
#' Default: \code{x.axis = "MONTH"}.

#' @param title (optional, character) Title to print on top of figure.
#' By default no title is displayed.
#' e.g. \code{title = "Manhattan plot of qPCR data by months and ecoregions"}.
#' Default: \code{title = NULL}.

#' @param free.scale (required, character) Should the scale of be free or fixed.
#' Available values: \code{free.scale = c("fixed", "free")}.
#' @param dashed.quartile (optional, logical) Display the Q25 and Q75 on the manhattan plot.
#' Default: \code{dashed.quartile = FALSE}.

#' @param dotted.mean (optional, logical) Display the mean frequency of detection on the manhattan plot.
#' Default: \code{dotted.mean = TRUE}.

#' @param color.palette (optional, character) Change the default color palette.
#' Available options are: \code{"viridis"}, ggplot2 basic colors: \code{"basic"} and
#' the ColorBrewer scales using \code{"brewer"}.
#' Default: \code{color.palette = "viridis"}.


#' @param height.override (optional, integer) Override the height of the plot.
#' Default: \code{height.override = NULL}.
#' @param width.override (optional, integer) Override the width of the plot.
#' Default: \code{width.override = NULL}.
#'
#' @param filename.prefix (optional, character) Filename prefix.
#' Default: \code{filename.prefix = NULL}.
#' @param path.folder (optional, character)
#' Default: \code{path.folder = NULL}. Default will use the working directory.
#' @param write.image (optional, logical) Write the figure in \code{path.folder}.
#' Default: \code{write.image = FALSE}.

#' @rdname qpcr_fig
#' @export
# @keywords internal
qpcr_fig <- function(
    data,
    manhattan = TRUE,
    heatmap = TRUE,
    ecoregion.select = NULL,
    taxon.select = NULL,
    species.select = NULL,
    year = FALSE,
    year.select = NULL,
    x.axis = "MONTH",
    title = NULL,
    free.scale = c("fixed", "free"),
    dashed.quartile = FALSE,
    dotted.mean = TRUE,
    color.palette = "viridis",
    height.override = NULL,
    width.override = NULL,
    filename.prefix = NULL,
    path.folder = NULL,
    write.image = FALSE
) {

  # # test
  # manhattan = TRUE
  # heatmap = TRUE
  # species.select = NULL
  # # species.select = "C. carcharias"
  # ecoregion.select = NULL
  # # year = FALSE
  # year = TRUE
  # # year.select = 2018
  # year.select = NULL
  # # taxon.select = NULL
  # taxon.select = "SPP"
  # # taxon.select = "PHYLUM"
  # # x.axis = "MONTH"
  # x.axis = "SPP"
  # title = NULL
  # free.scale = "fixed"
  # dashed.quartile = FALSE
  # dotted.mean = TRUE
  # color.palette = "viridis"
  # height.override = NULL
  # width.override = NULL
  # filename.prefix = NULL
  # path.folder = NULL
  # write.image = FALSE

  res <- list()

  if (is.null(path.folder)) path.folder <- getwd()

  # Filter dataset based on species SPP format
  if (!is.null(species.select)) {
    data %<>%
      dplyr::filter(SPP %in% species.select)
  }

  # Filter dataset based on ECOREGION
  if (!is.null(ecoregion.select)) {
    data %<>%
      dplyr::filter(ECOREGION %in% ecoregion.select) %>%
      dplyr::mutate(ECOREGION = droplevels(ECOREGION))
  }

  # Filter dataset based on YEAR
  if (!is.null(year.select) && year) {
    data %<>%
      dplyr::filter(YEAR %in% year.select) %>%
      dplyr::mutate(YEAR = droplevels(YEAR))
  }


  if (!is.null(taxon.select)) {
    taxon.select <- match.arg(
      arg = taxon.select,
      choices = c("KINGDOM", "PHYLUM", "CLASS", "ORDER", "FAMILY", "GENUS", "SCIENTIFIC_NAME", "SPP"),
      several.ok = FALSE
    )
    if (year) {
      want.month <- c("ECOREGION", taxon.select, "YEAR", "MONTH")
      want <- c("ECOREGION", taxon.select, "YEAR")

    } else {
      want.month <- c("ECOREGION", taxon.select, "MONTH")
      want <- c("ECOREGION", taxon.select)
    }
  } else {
    if (year) {
      want.month <- c("ECOREGION", "YEAR", "MONTH")
      want <- c("ECOREGION", "YEAR")

    } else {
      want.month <- c("ECOREGION", "MONTH")
      want <- c("ECOREGION")
    }
  }

  # prepare the data
  month.levels <- levels(data$MONTH)

  all.months <- data %>%
    dplyr::group_by(dplyr::pick({{ want }})) %>%
    dplyr::summarise(
      SAMPLING_EFFORT = dplyr::n(),
      FREQ_DETECTION = sum(DETECTED, na.rm = TRUE) / SAMPLING_EFFORT,
      .groups = "drop"
    ) %>%
    dplyr::mutate(MONTH = "ALL")


  data %<>%
    dplyr::group_by(dplyr::pick({{ want.month }})) %>%
    dplyr::summarise(
      SAMPLING_EFFORT = dplyr::n(),
      FREQ_DETECTION = sum(DETECTED, na.rm = TRUE) / SAMPLING_EFFORT,
      .groups = "drop"
    ) %>%
    dplyr::mutate(MONTH = as.character(MONTH)) %>%
    dplyr::bind_rows(all.months) %>%
    dplyr::mutate(MONTH = factor(MONTH, levels = c(month.levels, "ALL"))) %>%
    dplyr::group_by(dplyr::pick({{ want }})) %>%
    tidyr::complete(MONTH) %>%  # turn implicit missing values -> explicit missing values...
    dplyr::mutate(SAMPLING_EFFORT = tidyr::replace_na(SAMPLING_EFFORT, 0)) %>%
    dplyr::ungroup()

  all.months <- NULL

  # no NA in sampling effort
  # should find NA, O and numbers in detected
  if (anyNA(data$SAMPLING_EFFORT)) {
    rlang::abort("Error during data prep, contact author")
  }


  # group.color.name
  if (!is.null(taxon.select)) {
    if (taxon.select == "SPP") {
      group.color.name <- "SPECIES"
      taxon.filename <- "_SPECIES"
    } else {
      group.color.name <- taxon.select
      taxon.filename <- paste0("_", taxon.select)
    }
  } else {
      group.color.name <- NULL
      taxon.filename <- ""
  }


  free.scale <- match.arg(
    arg = free.scale,
    choices = c("fixed", "free"),
    several.ok = FALSE
  )

  data.stats <- data %>%
    dplyr::group_by(ECOREGION, MONTH) %>%
    dplyr::summarise(
      MEAN = mean(FREQ_DETECTION, na.rm = TRUE),
      # MEDIAN = stats::median(FREQ_DETECTION, na.rm = TRUE),
      # SD = stats::sd(FREQ_DETECTION, na.rm = TRUE),
      Q25 = stats::quantile(FREQ_DETECTION, 0.25, na.rm = TRUE),
      Q75 = stats::quantile(FREQ_DETECTION, 0.75, na.rm = TRUE),
      IQR = stats::IQR(FREQ_DETECTION, na.rm = TRUE),
      # MIN = min(FREQ_DETECTION, na.rm = TRUE),
      # MAX = max(FREQ_DETECTION, na.rm = TRUE),
      OUTLIERS_LOW = Q25 - (1.5 * IQR),
      OUTLIERS_HIGH = Q75 + (1.5 * IQR),
      .groups = "drop"
    ) %>%
    dplyr::mutate(
      MEAN = dplyr::if_else(is.na(MEAN), NA, MEAN),
      dplyr::across(where(is.numeric), ~ round(.x, digits = 6))
      ) %>%
    dplyr::arrange(MONTH)

  # manhattan ----------------------------------------------------------------
  if (manhattan) {

    .data <- NULL

    if (x.axis == "MONTH") {
      if (is.null(taxon.select)) {
        qpcr.manhattan <- ggplot2::ggplot(
          data = data,
          ggplot2::aes(x = ECOREGION, y = FREQ_DETECTION, size = as.numeric(SAMPLING_EFFORT)))
      } else {
        qpcr.manhattan <- ggplot2::ggplot(
          data = data,
          ggplot2::aes(x = ECOREGION, y = FREQ_DETECTION, size = as.numeric(SAMPLING_EFFORT), colour = .data[[taxon.select]]))
      }
    }

    if (x.axis == "SPP") {
      data %<>%
        dplyr::filter(MONTH != "ALL") %>%
        dplyr::mutate(MONTH = droplevels(MONTH))
      # data.stats %<>%
      #   dplyr::filter(MONTH != "ALL") %>%
      #   dplyr::mutate(MONTH = droplevels(MONTH))
      qpcr.manhattan <- ggplot2::ggplot(
        data = data,
        ggplot2::aes(x = ECOREGION, y = FREQ_DETECTION, size = as.numeric(SAMPLING_EFFORT), colour = MONTH))
      group.color.name <- "MONTH"
      dashed.quartile <- FALSE
      dotted.mean <- FALSE
    }

    qpcr.manhattan <- qpcr.manhattan +
      ggplot2::geom_jitter(alpha = 0.6, na.rm = TRUE, width = 0.9) +
      ggplot2::scale_y_continuous(name = "Frequency of detection (proportion)")

    if (color.palette == "viridis") {
      qpcr.manhattan <- qpcr.manhattan + ggplot2::scale_colour_viridis_d(name = group.color.name, option = "H")
    }
    if (color.palette == "brewer") {
      qpcr.manhattan <- qpcr.manhattan + ggplot2::scale_color_brewer(name = group.color.name)
    }
    if (color.palette == "basic") {
      qpcr.manhattan <- qpcr.manhattan + ggplot2::scale_color_discrete(name = group.color.name)
    }


    qpcr.manhattan <- qpcr.manhattan +
      ggplot2::scale_size_continuous(name = "SAMPLING EFFORT")

    if (!is.null(title)) {
      qpcr.manhattan <- qpcr.manhattan +
        ggplot2::labs(title = title)
    }



    qpcr.manhattan <- qpcr.manhattan +
      ggplot2::theme(
        panel.grid.major.x = ggplot2::element_blank(),
        plot.title = ggplot2::element_text(size = 12, family = "Helvetica", face = "bold", hjust = 0.5),
        plot.subtitle = ggplot2::element_text(size = 10, family = "Helvetica", hjust = 0.5),
        axis.line.x = ggplot2::element_blank(),
        axis.title.x = ggplot2::element_blank(),
        axis.text.x = ggplot2::element_blank(),
        axis.ticks.x = ggplot2::element_blank(),
        axis.title.y = ggplot2::element_text(size = 10, family = "Helvetica", face = "bold"),
        axis.text.y = ggplot2::element_text(size = 8, family = "Helvetica"),
        legend.title = ggplot2::element_text(size = 10, family = "Helvetica", face = "bold")
      )



    if (taxon.select == "SPP" && x.axis == "MONTH") {
      qpcr.manhattan <- qpcr.manhattan +
        ggplot2::guides(color = ggplot2::guide_legend(label.theme = ggplot2::element_text(size = 8, family = "Helvetica", face = "italic")))
    }

    if (dashed.quartile) {
      qpcr.manhattan <- qpcr.manhattan +
        ggplot2::geom_hline(mapping = ggplot2::aes(yintercept = Q25),
                            data.stats, linetype = "dashed", linewidth = 0.6, na.rm = TRUE) + #Q25
        ggplot2::geom_hline(mapping = ggplot2::aes(yintercept = Q75),
                            data.stats, linetype = "dashed", linewidth = 0.6, na.rm = TRUE)  #Q75
    }

    if (dotted.mean) {
      qpcr.manhattan <- qpcr.manhattan +
        ggplot2::geom_hline(mapping = ggplot2::aes(yintercept = MEAN),
                            data.stats, linetype = "dotted", linewidth = 0.6, na.rm = TRUE)#mean
    }

    if (!is.null(taxon.select)) {
      n.taxon <- dplyr::n_distinct(data[[taxon.select]])
    } else {
      n.taxon <- 1L
    }

    n.group <- dplyr::n_distinct(data$ECOREGION)

    if (x.axis == "MONTH") {
      if (year) {
        qpcr.manhattan <- qpcr.manhattan +
          ggplot2::facet_grid(ECOREGION + YEAR ~ MONTH, scales = free.scale)
        n.year <- dplyr::n_distinct(data$YEAR)
        year.filename <- "_YEAR"
      } else {
        qpcr.manhattan <- qpcr.manhattan +
          ggplot2::facet_grid(ECOREGION ~ MONTH, scales = free.scale)
        n.year <- 1L
        year.filename <- ""
      }
    }

    if (x.axis == "SPP") {
      if (year) {
        n.year <- dplyr::distinct(data, YEAR, ECOREGION) %>% nrow
        if (n.taxon > n.year) {
          qpcr.manhattan <- qpcr.manhattan +
            ggplot2::theme(strip.text.y = ggplot2::element_text(angle = 0)) +
            ggplot2::facet_grid(SPP + YEAR ~ ECOREGION, scales = free.scale)
        } else {
          qpcr.manhattan <- qpcr.manhattan +
            # ggplot2::theme(strip.text.y = ggplot2::element_text(angle = 0)) +
            ggplot2::facet_grid(ECOREGION + YEAR ~ SPP, scales = free.scale)
        }
        year.filename <- "_YEAR"
      } else {
        if (n.taxon > n.group) {
          qpcr.manhattan <- qpcr.manhattan +
            ggplot2::theme(strip.text.y = ggplot2::element_text(angle = 0)) +
            ggplot2::facet_grid(SPP ~ ECOREGION, scales = free.scale)
        } else {
          qpcr.manhattan <- qpcr.manhattan +
            ggplot2::theme(strip.text.y = ggplot2::element_text(angle = 0)) +
            ggplot2::facet_grid(ECOREGION ~ SPP, scales = free.scale)
        }
        n.year <- 1L
        year.filename <- ""
      }
    }

    print(qpcr.manhattan)

    if (write.image) {
      # Figure filename
      if (is.null(filename.prefix)) {
        filename.prefix.qpcr <- "qpcr_manhattan_plot"
      } else {
        filename.prefix.qpcr <- paste0(filename.prefix, "_qpcr_manhattan_plot")
      }

      qpcr.fig.filename <- paste0(filename.prefix.qpcr, year.filename, taxon.filename)

      if (is.null(height.override)) height.override <- max(n.group * n.year + n.taxon, 20L)
      if (is.null(width.override)) width.override <- NA

      # write figures
      ggplot2::ggsave(
        filename = file.path(path.folder, paste0(qpcr.fig.filename, ".pdf")),
        plot = qpcr.manhattan,
        width = width.override,
        height = height.override,
        dpi = 600,
        units = "cm",
        useDingbats = FALSE,
        limitsize = FALSE
      )

      ggplot2::ggsave(
        filename = file.path(path.folder, paste0(qpcr.fig.filename, ".png")),
        plot = qpcr.manhattan,
        width = width.override,
        height = height.override,
        dpi = 200,
        units = "cm",
        limitsize = FALSE
      )
    }
      res$qpcr.manhattan <- qpcr.manhattan

    }# End manhattan



  # heatmap ------------------------------------------------------------------

  if (heatmap) {
    qpcr.heatmap <- ggplot2::ggplot(
      data = data,
      ggplot2::aes(x = MONTH, y = ECOREGION, fill = FREQ_DETECTION)
    ) +
      ggplot2::geom_tile(color = "white", alpha = 0.7) +
      ggplot2::geom_text(ggplot2::aes(x = MONTH, y = ECOREGION, label = SAMPLING_EFFORT),
                         color = "black", size = 3, family = "Helvetica", fontface = "bold", na.rm = TRUE) +
      ggplot2::scale_fill_viridis_c(name = "Frequency of detection\n(proportion)", option = "H", na.value = "white") +
      ggplot2::scale_x_discrete(position = "top") +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.title.x = ggplot2::element_blank(),
        axis.title.y = ggplot2::element_blank(),
        # axis.text.x = ggplot2::element_text(size = 10, family = "Helvetica", face = "bold"),
        # axis.text.y = ggplot2::element_text(size = 10, family = "Helvetica", face = "bold")
        axis.text.x = ggplot2::element_blank(),
        axis.text.y = ggplot2::element_blank()
      )

    if (!is.null(taxon.select)) {
      n.taxon <- dplyr::n_distinct(data[[taxon.select]])
    } else {
      n.taxon <- 1L
    }
    n.group <- dplyr::n_distinct(data$ECOREGION)

    if (year) {
      if (is.null(taxon.select)) {
        qpcr.heatmap <- qpcr.heatmap +
          ggplot2::facet_grid(ECOREGION + YEAR ~ MONTH, scales = "free")
      } else {
        qpcr.heatmap <- qpcr.heatmap +
          ggplot2::facet_grid(ECOREGION + YEAR + SPP ~ MONTH, scales = "free")
      }

      n.year <- dplyr::n_distinct(data$YEAR)
      year.filename <- "_YEAR"
    } else {

      if (is.null(taxon.select)) {
        qpcr.heatmap <- qpcr.heatmap +
          ggplot2::facet_grid(ECOREGION ~ MONTH, scales = "free")
      } else {
        qpcr.heatmap <- qpcr.heatmap +
          ggplot2::facet_grid(stats::as.formula(paste(taxon.select, "+ ECOREGION", "~", "MONTH")), scales = "free")

      }

      # as.formula(paste("~", group_var)
      # ggplot2::facet_grid(PHYLUM + ECOREGION ~ MONTH, scales = "free")#, labeller = ggplot2::labeller(TX = taxon.select))

      n.year <- 1L
      year.filename <- ""
    }


    # qpcr.heatmap
    print(qpcr.heatmap)

    if (write.image) {

      filename.prefix.qpcr <- filename.prefix
      if (is.null(filename.prefix)) {
        filename.prefix.qpcr <- "qpcr_heatmap_plot"
      } else {
        filename.prefix.qpcr <- paste0(filename.prefix, "_qpcr_heatmap_plot")
      }

      qpcr.fig.filename <- paste0(filename.prefix.qpcr, year.filename, taxon.filename)


      if (is.null(height.override)) height.override <- max(n.group * n.year  + n.taxon, 25L)
      if (is.null(width.override)) width.override <- NA


      ggplot2::ggsave(
        filename = file.path(path.folder, paste0(qpcr.fig.filename, ".png")),
        plot = qpcr.heatmap,
        width = width.override,
        height = height.override,
        dpi = 200,
        units = "cm",
        device = "png",
        limitsize = FALSE)

      ggplot2::ggsave(
        filename = file.path(path.folder, paste0(qpcr.fig.filename, ".pdf")),
        plot = qpcr.heatmap,
        width = width.override,
        height = height.override,
        dpi = 600,
        units = "cm",
        device = "pdf",
        limitsize = FALSE,
        useDingbats = FALSE)
    }

    res$qpcr.heatmap <- qpcr.heatmap
  } #End heatmap



  return(res)
} # End qpcr_vis
